services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/services/homes/MartBent/Git/home-lab/ha:/config

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    network_mode: host
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - NODE_ENV=production
      - N8N_RELEASE_TYPE=stable
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      - SUBDOMAIN=${N8N_SUBDOMAIN}
      - N8N_HOST=${N8N_SUBDOMAIN}.${N8N_DOMAIN}
      - DOMAIN_NAME=${N8N_DOMAIN}
      - WEBHOOK_URL=https://${N8N_SUBDOMAIN}.${N8N_DOMAIN}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: host
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  n8n_data:
